[package]
name = "ghidorah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.2"
native-tls = "0.2.11"
tungstenite = {version = "0.21.0", features = ["native-tls"]}
url = "2.5.0"
